apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T12:24:54Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5278"
  uid: 301ca855-a4dc-45a7-a697-2ae9693f75e8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.227.129
  clusterIPs:
  - 10.101.227.129
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31054
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
